name: Build CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with make
        run: make --directory="./source/" build_host_description="${CI_HOST_INFO} ID:${GITHUB_RUN_ID} for ${GITHUB_REF}"
      - name: Upload executable file
        uses: actions/upload-artifact@v4
        env:
          CI_HOST_INFO: GitHub Build CI
        with:
          name: i18nglish-linux
          path: ./source/i18nglish.out
          if-no-files-found: error
          retention-days: 1
